/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf9fc',
        'surface-dim': '#dad9dd',
        'surface-bright': '#faf9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f6',
        'surface-container': '#eeedf1',
        'surface-container-high': '#e9e8eb',
        'surface-container-highest': '#e3e2e5',
        'on-surface': '#111827',
        'on-surface-variant': '#4b5563',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        outline: '#73777f',
        'outline-variant': '#c3c6cf',
        'surface-tint': '#436085',
        primary: '#53617a',
        'on-primary': '#ffffff',
        'primary-container': '#e48b59',
        'on-primary-container': '#9cbae4',
        'inverse-primary': '#abc9f3',
        secondary: '#875200',
        'on-secondary': '#ffffff',
        'secondary-container': '#fead48',
        'on-secondary-container': '#6f4300',
        tertiary: '#003b21',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#005431',
        'on-tertiary-container': '#7cc799',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf9fc',
        'on-background': '#1a1c1e',
        'surface-variant': '#e3e2e5',
        border: '#d8dadf',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['"Archivo Narrow"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['15px', { lineHeight: '22px' }],
        'label-caps': ['13px', { lineHeight: '18px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-mono': ['15px', { lineHeight: '22px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        gutter: '12px',
        unit: '4px',
        'container-padding': '16px',
        'row-height-dense': '40px',
        'row-height-standard': '48px',
      },
      height: {
        'row-height-standard': '40px',
        'row-height-dense': '32px',
      },
    },
  },
  plugins: [],
};
